#!/bin/sh


mv -v ./week-01/accomplishment-report.ms ./
mv -v ./week-01/Sep-26-2022-Mon.ms ./
mv -v ./week-01/Sep-27-2022-Tue.ms ./
mv -v ./week-01/Sep-28-2022-Wed.ms ./
mv -v ./week-01/Sep-29-2022-Thu.ms ./
mv -v ./week-01/Sep-30-2022-Fri.ms ./
mv -v ./week-02/accomplishment-report.ms ./
mv -v ./week-02/Oct-3-2022-Mon.ms ./
mv -v ./week-02/Oct-4-2022-Tue.ms ./
mv -v ./week-02/Oct-5-2022-Wed.ms ./
mv -v ./week-02/Oct-6-2022-Thu.ms ./
mv -v ./week-02/Oct-7-2022-Fri.ms ./
mv -v ./week-03/Oct-10-2022-Mon.ms ./
mv -v ./week-03/Oct-11-2022-Tue.ms ./
mv -v ./week-03/Oct-12-2022-Wed.ms ./
mv -v ./week-03/Oct-13-2022-Thu.ms ./
mv -v ./week-03/Oct-14-2022-Fri.ms ./
mv -v ./week-04/Oct-17-2022-Mon.ms ./
mv -v ./week-04/Oct-18-2022-Tue.ms ./
mv -v ./week-04/Oct-19-2022-Wed.ms ./
mv -v ./week-04/Oct-20-2022-Thu.ms ./
mv -v ./week-04/Oct-21-2022-Fri.ms ./
mv -v ./week-05/Oct-24-2022-Mon.ms ./
mv -v ./week-05/Oct-25-2022-Tue.ms ./
mv -v ./week-05/Oct-26-2022-Wed.ms ./
mv -v ./week-05/Oct-27-2022-Thu.ms ./
mv -v ./week-05/Oct-28-2022-Fri.ms ./
mv -v ./week-06/Nov-3-2022-Thu.ms ./
mv -v ./week-06/Nov-4-2022-Fri.ms ./
