.TL
End of the Day Report
.AU
Mark Nhel A. Besonia
.AI
Innovūze Solutions, Inc
.DA

.QP
.IP \(bu 2
Configured
.I "rsyslog"
in
.I "lxd"
container to send and recieve logs from other containers.
.IP \(bu 2
Installed and configured
.I "supervisord"
in an
.I "lxd"
container.
.IP \(bu 2
Configured
.I "supervisord"
to autostart
.I "nginx"
and
.I "rsyslog"
to be accessed and monitored through its webserver.
