.TL
End of the Day Report
.AU
Mark Nhel A. Besonia
.AI
Innovūze Solutions, Inc
.DA

.QP
.IP \(bu 2
Learned port forwarding and using
.I "iptables"
with
.I "lxd".
.IP \(bu 2
Implemented port forwarding in
.I "ssh"
and forwarded ssh in my host machine to an lxd container.
.IP \(bu 2
Studied reverse proxy using
.I "nginx".
.IP \(bu 2
Implemented reverse proxy using
.I "nginx"
and redirected all https traffic to an lxd container running a django application.
