.TL
End of the Day Report
.AU
Mark Nhel A. Besonia
.AI
Innovuze Solutions, Inc.
.DA

.QP
.IP \(bu 2
Research further about OPNsense for the future set up.
.IP \(bu 2
Our supervisor, Sir Arnold Gutib, together with Sir Leo Teves showed us the server room and oriented us about the servers and gave us instructions on how should we respond in case of internet connection loss and when the servers are down.
