.TL
End of the Day Report
.AU
Mark Nhel A. Besonia
.AI
Innovuze Solutions, Inc.
.DA

.QP
.IP \(bu 2
Keeping check on the servers and firewall.
.IP \(bu 2
Made a significant progress (i.e. configuring users, adding and configuring different kinds of network interfaces, installing and updating OPNsense packages and plugins, restricting a network interface's bandwidth, and adding and removing client ) in an OPNsense firewall.
